<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>6cd584d3-c08c-4475-837d-427f8138c6ee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Aspire hosting integrations">
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup Label="Orchestrated services">
    <ProjectReference Include="../AiService/AiService.csproj" />
  </ItemGroup>

</Project>
